### ISSUE TITLE
Support for acrylic Brush

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/fluent-xaml-theme-editor#12]
## Feature Request

Support for built in **ThemeResources** based **AcrylicBrush**, both the in-app acrylic and the window-acrylic ( when you window of your app is transparent to other apps ). Since the theme editor only deals with dark and light theme resources, I think custom acrylic doesn't make any sense here ( correct me if I am wrong ).

**Comment by mdtauk** [comment]
The AcrylicBrushes are tinted in either White or Black to match the Light or Dark themes.  If the Region colour is not White or Black, then the AcrylicBrush should match in both its Active and Inactive states (the fallback colour)

**Comment by touseefbsb** [comment]
yes obviously fallback color is also important, acrylic is composed of 3 brushes as @kikisaints  mentioned in other thread.

**Comment by kikisaints** [comment]
@mdtauk That's a good rationale for what to actually set the AcrylicBrushes' system colors too. 

What @touseefbsb is referring to are these two SystemColors that the editor does not generate today:

```xaml
<Color x:Key="SystemChromeAltMediumHighColor">#CCFFFFFF</Color>
<Color x:Key="SystemChromeAltHighColor">#FFFFFFFF</Color>
```
He's suggesting that we add those as generated colors, even if they are just pulling their color values from the Region color, as you suggested.

As far as the fallback colors as concerned, they are pulling from a variety of different SystemColors that the editor does generate, so those should be accounted for.

**Comment by mdtauk** [comment]
@kikisaints I think if the Fluent Editor is going to be of the most use, then it should replace all the referenced colours that the controls need to be fully themed - Including the Acrylic ones.  The ColorPaletteResources code could be updated in the future to fully encompass all resources needed.

**Comment by touseefbsb** [comment]
yes agreed, even if 1 resource is not generated by theme editor , who knows where it might cause visual problems in the app in which control.

**Comment by kikisaints** [comment]
#14 PR has been completed. The generated code should now export the necessary Acrylic and Reveal SystemColors.

**Comment by touseefbsb** [comment]
Thanks for the quick fix @kikisaints  :)
