### ISSUE TITLE
NavigationView ( winui ) items not getting the hover color

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/fluent-xaml-theme-editor#16]
Just tried and exported the preset Forest theme into my app, and noticed that there is no hover effect, ( when I hover on the navigationviewitem there is no effect or color change whatsoever. Also same problem occurs with the back button of the NavigationView, but the menu toggle button gets the hover color change as expected.

In this image my pointer is actually on Library and you can see that library and home basically have same color.

![2018-10-16 2](https://user-images.githubusercontent.com/11542189/47051445-bf1a5c00-d1bd-11e8-84f8-cb1eba80e2b8.png)

**Comment by kikisaints** [comment]
Does this bug repo only when using WinUI, or are you seeing this with and without?

**Comment by touseefbsb** [comment]
with and without.

**Comment by kikisaints** [comment]
Interesting - couple of other questions then :smile: were you in low power/battery saver mode and/or do you have transparency effects on or off? That's an option in Settings>Personalization>Colors under "More Options":

![image](https://user-images.githubusercontent.com/6964369/47174084-929d3780-d2c4-11e8-8412-de2b4fcea93d.png)

**Comment by touseefbsb** [comment]
@kikisaints  I am testing on a Azure VM and I can see the hover color when I dont apply theme editor resources to my app ( using default ) so I dont think that is the problem in this scenario, although VM doesnt show all settings and my app doesnt show acrylic and reveal on my 1809 VM, so I guess transparency effects might be turned off there, can you not reproduce this issue on your machine?

**Comment by touseefbsb** [comment]
That is a possibility, yes. I am no expert on VMs turning off certain features, but it looks like you cannot reproduce the issue, which means my VM is probably the cause here. And about the contrast, the hover can be a little darker I think :)
