### ISSUE TITLE
this doesn't work... The instructions are a statement rather than how to use this

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/fluent-xaml-theme-editor#20]
please review the readme for usability 

p.s.

how do you use this and what do you do with it.

**Comment by kikisaints** [comment]
Can you clarify what you mean by "doesn't work"? 

I'll update the readme to be clearer - in the meantime this editor simply generates code that you can use in a ResourceDictionary within XAML. If you're curious about the exact flow, you can go check out the [blog post on this tool here](https://blogs.windows.com/buildingapps/2018/10/10/fluent-xaml-theme-editor-preview-released/).

**Comment by touseefbsb** [comment]
how about including some more stuff from blogpost into readme as well ?

**Comment by kikisaints** [comment]
@touseefbsb You read my mind! I went ahead and added the blog post info to the readme :smile:

@xtianus79 please go check out the newest addition to the [readme file here](https://github.com/Microsoft/fluent-xaml-theme-editor/blob/master/README.md#how-to-use-the-tool) and let me know if that helps you get a better understanding of how to use the tool.

**Comment by touseefbsb** [comment]
yeah I wanted that info here for myself as well :D
