### ISSUE TITLE
Add Acrylic material in the sample app

### ISSUE THREAD

**Issue by touseefbsb** [microsoft/fluent-xaml-theme-editor#24]
In order to show the developers how they can use acrylic with their custom themes and how exactly it will look like I suggest that there must be some sample controls on the sample app on both the light and dark sides which show the acrylic according to the theme selected. This will include both the window and the element acrylic ( hos acrylic and in-app acrylic ) and will also include multiple opacity's as shown in official docs of acrylic.

May I also suggest some comments on the exported resources, so that each color/resource can have a comment explaining the purpose of that specific resource, and in case of RegionColor, a commend can explain why exactly it needs to be manually applied, and where and in what cases it is needed

**Comment by touseefbsb** [comment]
@kikisaints  any update on this?

**Comment by kikisaints** [comment]
Sorry! Just recently was able to get around to working on this - I'll let you know once I've got something 😅

**Comment by touseefbsb** [comment]
oh alright :)

**Comment by kikisaints** [comment]
So it looks like the SystemColor that acrylic uses isn’t built into the ColorPaletteResources API, which means that the scoping functionality that the editor uses to display your live changes won’t be able to show a live updated acrylic. 

I’ll look into adding this SystemColor to the ColorPaletteResources API, but at this time I don’t think I can update the editor to show acrylic. The exported theme should still affect acrylic because of the fact I’m forcing it to export that extra SystemColor. 

For my own sake, I’m going to keep this bug up so I can track it and not forget.

**Comment by touseefbsb** [comment]
ahan fair enough, as far as we can get acrylic in the exported theme, that should work :)

**Comment by kikisaints** [comment]
Yes, the exported theme should affect Acrlyic - are you using the theme in conjunction with WinUI?

**Comment by touseefbsb** [comment]
yes I am using theme in conjunction with WINUI. but I have not applied region color anywhere as it seemed to me all of my app was already reflecting the required theme apart from acrylic ( mainly window acrylic ) but I supposed region color doesn't effect acrylic?

**Comment by kikisaints** [comment]
Region color won't effect Acrylic, as it's just an abstract brush we create for you to apply to a Grid or container background of your choice.

However, could you do me a favor and try your same exported theme without WinUI? We were running into issues where WinUI was stomping over local definitions of our system resources. Curious if that's what's happening in your situation...

**Comment by touseefbsb** [comment]
actually I am mainly using the NavigationView from winui library, and it is deeply implemented into the app , ( lot of front end and backend complex logic has already been wired upto the navigationview control ) so it might be really hard to test without winui right now.

**Comment by kikisaints** [comment]
Completed as of the most recent PR.
