### ISSUE TITLE
What are the keys in primary colors?

### ISSUE THREAD

**Issue by doghappy** [Microsoft/fluent-xaml-theme-editor#28]
![image](https://user-images.githubusercontent.com/20038914/54678897-00ce7a80-4b41-11e9-80da-8ffb0f23c013.png)

**Comment by kikisaints** [comment]
I'm not sure what you mean by keys - do you mean what parts of the controls do they hook up to?

**Comment by doghappy** [comment]
When I changed the `Primary Color`, it seems that the program automatically generates other colors based on `Primary Color`, I want to use these colors, but I don't know what the keys are.

**Comment by kikisaints** [comment]
Oh! That's our algorithm that generates a palette. If you want to use any of those colors, you can do so by creating a color tag and plugging in any of the hex values you see provided in the palette.

For example, if you wanted to use the first color in the Light Primary palette stack, do:

``` xaml
<Color x:key="myTealBlueLight1">#ff9BF3E7</Color>
```

Not all of the colors generated are used by the system, but we create the whole palette, so we give you the hex values to use at your own discretion if you want to.
