### ISSUE TITLE
Why the current, multi-project, architecture?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/fluent-xaml-theme-editor#3]
Why is there a shared project and a main app project?
The code in the shared project seems very specific to the FXTE.
Also, it's not shared with anything else. Is this an indication that there may be other, related projects added to the solution or is it just a historical artifact?
If a historical artifact, would suggestions for simplifying/rationalizing the code be welcome?

**Comment by kikisaints** [comment]
The FluentEditorShared folder is a library that our design team uses and parts of it are called by the main FluentEditor solution. Things like an RGB to HSV converter and contrast ratio checker functions are among the ones I know of that are being used.

**Comment by mrlacey** [comment]
@kikisaints thanks for the input on the other use of the library. I won't suggest any changes there then. ;)
