### ISSUE TITLE
Color picker breaks when using certain system scaling percentages.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/fluent-xaml-theme-editor#32]
The color picker(s) behave very erratically / incorrectly when system scaling is set to 125%, 175%, 225%, and probably some other uneven values.

The WinUI color picker doesn't exhibit this behavior in the XAML Controls Gallery, so I'm not sure if the issue is related to it being housed in a popup / flyout / overlay or something else.

**Comment by kikisaints** [comment]
I think this might be a WinUI issue... we had an issue like this in the past. Have you logged an issue over on the [WinUI Repo](https://github.com/Microsoft/microsoft-ui-xaml)?

**Comment by kmgallahan** [comment]
Not yet as I wasn't sure how to repro the issue outside of this app. 

Like I said, it works fine in the Gallery app, so not sure if the behavior is related to the specific way it is being presented in this app or not. Also unsure about the version being used.

Was hoping the maintainer(s) here could share some incite first, but I could just go ahead and open a WinUI ticket and link this issue if you'd prefer.

**Comment by kikisaints** [comment]
I'm the only maintainer of the repo, so I'll look into what might be causing it 😅

**Comment by kikisaints** [comment]
@kmgallahan so I tested the colorpicker at different scaling and I'm not seeing an issue... however I know there was an older issue logged on WinUI about ColorPicker scaling.

Could you clarify more about the erratic behavior you're seeing? Additionally, I will be pushing an updated winUI package for this app, so it could be a bug from an older version.

**Comment by kmgallahan** [comment]
First two screenshots show the picker at 125% scaling. Bugs:

- The color picker background is gone/transparent
- The selected color indicator appears in different places from where the cursor actual is (always appearing in the box, but nearly random locations)

*Note I made a red mark in the screenshots to indicate the cursor position since the screen cap didn't grab it

![Annotation 2019-10-21 122717](https://user-images.githubusercontent.com/5379488/67224421-24231600-f3ff-11e9-81be-4331d1a54a99.png)
![Annotation 2019-10-21 122717b](https://user-images.githubusercontent.com/5379488/67224406-1bcadb00-f3ff-11e9-87bb-c761bac8e43a.png)

This screenshot shows the picker at 100% scaling (working properly):

![Annotation 2019-10-21 122717c](https://user-images.githubusercontent.com/5379488/67224375-0a81ce80-f3ff-11e9-8c57-149f32542d06.png)

**Comment by kmgallahan** [comment]
Just had a though - it may be related to the use of an acrylic background under the control. The composition engine would then be doing _something_ different here, compared to most other instances of this control. 

Nope. Just turned off transparency effects and it made no difference.

**Comment by kikisaints** [comment]
Sorry for the delay on this!

Looks like the issue you're running into is a spotty one - meaning we cannot reliably test it on our machines and have only seen it on a select few builds. Additionally, repos have been on the control or test apps, not just localized to this app necessarily, although it is weird that you don't see it in the gallery.

I have let @jevansaks know, but as it goes right now, since I cannot recreate this on my own machine I can't make too much progress towards solving it unfortunately...

I will be pushing out an update to the app that will have an updated WinUI package as well. When that happens please try it out and see if there's still an issue.

**Comment by kmgallahan** [comment]
Closing as the behavior no longer occurs in the latest release.
