### ISSUE TITLE
licensing related, can we include this with our UWP app which we are selling

### ISSUE THREAD

**Issue by rahulkps23** [microsoft/fluent-xaml-theme-editor#42]
We are developing and selling a UWP app for our client as per his requirement. He wants to change the theme easily, so found this theme changing functionality of 'fluent-xaml-theme-editor' interesting. 

Can we bundle this along with our uwp app and sell (or) is this any license related issue?

Can anyone give clarity.

@kikisaints

**Comment by mrlacey** [comment]
IANAL, but, as per [the license](https://github.com/microsoft/fluent-xaml-theme-editor/blob/master/LICENSE), yes.

**Comment by kikisaints** [comment]
Yes, technically you can.
