### ISSUE TITLE
Distribution through the Microsoft Store

### ISSUE THREAD

**Issue by ghost** [microsoft/fluent-xaml-theme-editor#8]
I just want to know if there is any plan of taking this tool to the Microsoft Store, I think it will be a thing _nice to have_ to improve discoverability and ease of use although there's no hurry.  
What do you think?

**Comment by mdtauk** [comment]
Once it is fully working, putting it in the store is the best option

**Comment by kikisaints** [comment]
Yes! I'm working on an app submission to the store! It will come, don't worry 👍
